{
 "title": "SpringBoot_GrafanaDashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 7, "y": 0 },
   "content": "\n# CarService CRUD Grafana Dashboard\n\n\n"
  },
  {
   "title": "System Load",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(system_load_average_1m)" }
   ]
  },
  {
   "title": "CPU Auslastung",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_cpu_usage" }
   ]
  },
  {
   "title": "Requests per Minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_gc_memory_allocated_bytes_total"
    }
   ]
  }
 ]
}